### ISSUE TITLE
シングルバックスラッシュがどうしても出ない

### ISSUE THREAD

**Issue by kosugitti** [ykunisato/jpaRmd#2]
引用形式を整えたTeXコードを履く関数を作っているなかで，問題にぶつかっています。

Rのエスケープ記号としての \ が \\ としてしか出せず，これがTeXで出すときのネックになっています。
イメージとしてはRmdファイルの中で関数を実行すればOKというようにしたかったのですが，この壁が超えられそうにありません。
そこで，引用文献関数が一旦bibfile_tmp.texのようにtexファイルを書き出して，それをincludeしたものをコンパイルするようにしてもらえれば，というのを考えました。フィルに出力すると，二重バックスラッシュがシングルになるのですが。

あるいは何かお知恵を拝借できれば。

**Comment by kazutan** [comment]
なんか以前に対応したことがあるような……
具体的にはどこの処理か、教えてもらえますか？

**Comment by kosugitti** [comment]
原稿を書いているRmdファイルで関数を実行すると，TeX加工された文献リストを出力する，を目標にしています。
TeXでは強調・イタリックに\emph{hogehoge}という感じで書きますが，これが\\emphかemphにしかならなくて困っています。
一旦ファイル出力させると\emphになるのですが，ファイル出力したものをRmdで読み込んでコンパイルできますでしょうか。できるならそっちのほうが早いかも・・・と思ってます。

**Comment by kosugitti** [comment]
悩む箇所がここじゃない気がしてきたので，一旦このIssueを閉じます。
