### ISSUE TITLE
3名以上の共著の引用でも初出から「他」・「et al.」で略記するようになったことへの対応

### ISSUE THREAD

**Issue by SATO-yo** [ykunisato/jpaRmd#60]
いつも大変お世話になっております。
APAスタイル第7版から、3名以上の共著を引用する際に、初出でも "et al." で略記するようになりました。また、これに合わせて日本心理学会の執筆・投稿の手引きでも初出から「他」・「et al.」で略記するように定めています。
jpaRmd::render_jjp でもこれに合わせるか、引数で略記の開始タイミングを初出からにするか2回目からにするかを選択できるようにしていただくことは可能でしょうか。
お手すきの際で構いませんので、ご検討をよろしくお願いいたします。

**Comment by ykunisato** [comment]
コメントありがとうございます。ご指摘ありがとうございます。@kosugitti と相談しつつ対応させていただきます。

**Comment by ykunisato** [comment]
@SATO-yo @kosugitti に引用の設定を変更してもらいました。再インストールいただいて，RmdのYAMLで，use.et.al.first: Tとしていただくと，初出から「et al」「他」表記になります。

output:
  jpaRmd::render_jjp:
    Rmd_file: Untitled.Rmd
    Bib_file: reference.bib
    use.et.al.first: T

**Comment by SATO-yo** [comment]
早速ありがとうございました。
use.et.al.first: T とすることで、日本語文献でも英語文献でも、初出から正しく略記されました。

**Comment by ykunisato** [comment]
問題が解決しましたのでissueを閉じます。
